name: Deploy Project
on : 
    push :
     branches : main #branch activity types
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name : test react app 
            run : echo "test react app"
          - name: install Node js
            uses: actions/setup-node@v3
            with:
                node-version: 18
          - name: install dependancies 
            run: npm ci
          - name: run tests
            run: npm test 
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name : test react app 
            run : echo "test react app"
          - name: install Node js
            uses: actions/setup-node@v3
            with:
                node-version: 18
          - name: install dependancies 
            run: npm ci
          - name: build Project 
            run: npm run build
          - name: deploy project
            run: echo "Deploying ....."
          - name: Upload Files
            uses: actions/upload-artifact@v3
            with:
                name: dist-files
                path: | 
                    dist
                    package.json              
        
